apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: turkiznazaba/customers:2024-01-04-12-15-21 #to be changed
          name: customers
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com:5432/hdalyqbh
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: hdalyqbh
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbpasswordcustomers
                  key: dbpasswordcustomers
            - name: URL_APPOINTMENTS
              value: http://20.242.208.205/appointments/v1/appointments


          ports:
            - containerPort: 8081
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: customers
