#        - image: turkiznazaba/appointments:2023-12-01-09-21-36 #to be changed

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: turkiznazaba/customers:2023-12-26-14-09-53 #to be changed
          name: customers
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com:5432/hdalyqbh
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: hdalyqbh
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: EfjnbNxlNDRLpxrUMApVIXn1L9meZ2Tb
            #            - name: KUMULUZEE_DATASOURCES0_PASSWORD
            #              valueFrom:
            #                secretKeyRef:
            #                  name: dbpassword
            #                  key: dbpassword
            - name: URL_APPOINTMENTS
#              value: http://20.81.4.29:8080/v1/appointments
              value: http://20.242.208.205/appointments/v1/appointments


          ports:
            - containerPort: 8081
              name: server
#          livenessProbe:
#            httpGet:
#              path: /health/live
#              port: server
#            initialDelaySeconds: 20
#            periodSeconds: 3
#          readinessProbe:
#            httpGet:
#              path: /health/ready
#              port: server
#            initialDelaySeconds: 20
#            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: customers
